---
# --------------------------------

- name: "Zookeeper group"
  ansible.builtin.group:
    name: "{{ zookeeper_user }}"
    state: present
  become: true
  tags: [ct-zookeeper]

- name: "Zookeeper user"
  ansible.builtin.user:
    comment: "Zookeeper"
    group: "{{ zookeeper_user }}"
    name: "{{ zookeeper_user }}"
    state: present
  become: true
  tags: ct-zookeeper

- name: "Create Zookeeper staging dir"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ zookeeper_staging_dir }}"
    state: directory
  tags: [ct-zookeeper]

- name: "Create Zookeeper install dir"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ zookeeper_install_dir }}"
    state: directory
  become: true
  tags: [ct-zookeeper]

- name: "Create Zookeeper data dir"
  ansible.builtin.file:
    group: "{{ zookeeper_user }}"
    mode: "0755"
    owner: "{{ zookeeper_user }}"
    path: "{{ zookeeper_data_dir }}"
    state: directory
  become: true
  tags: [ct-zookeeper]

- name: "Create Zookeeper logs dir"
  ansible.builtin.file:
    group: "{{ zookeeper_user }}"
    mode: "0755"
    owner: "{{ zookeeper_user }}"
    path: "{{ zookeeper_logs_dir }}"
    state: directory
  become: true
  tags: [ct-zookeeper]

- name: "Download Zookeeper archive"
  ansible.builtin.get_url:
    dest: "{{ zookeeper_staging_dir }}/{{ zookeeper_tarball }}"
    mode: "0644"
    timeout: "{{ zookeeper_internet_timeout }}"
    url: "{{ zookeeper_url }}"
    validate_certs: false
  tags: [ct-zookeeper]

- name: "Expand Zookeeper archive"
  ansible.builtin.unarchive:
    copy: false
    dest: "{{ zookeeper_install_dir }}"
    extra_opts: ["--strip-components=1"]
    src: "{{ zookeeper_staging_dir }}/{{ zookeeper_tarball }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [ct-zookeeper]

- name: "Render Zookeeper config file"
  ansible.builtin.template:
    dest: "{{ zookeeper_config_dir }}/zoo.cfg"
    mode: "0644"
    src: zoo.cfg.j2
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [ct-zookeeper]

- name: "Render Zookeeper myid file"
  ansible.builtin.template:
    dest: "{{ zookeeper_data_dir }}/myid"
    mode: "0644"
    src: myid.j2
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [ct-zookeeper]

- name: "Render Systemd unit file"
  ansible.builtin.template:
    dest: /etc/systemd/system/zookeeper.service
    group: root
    mode: "0644"
    owner: root
    src: zookeeper.service.j2
  register: reg_service
  become: true
  tags: [ct-zookeeper]

- name: "Enable Zookeeper service"
  ansible.builtin.systemd:
    daemon_reload: "{{ reg_service is changed }}"
    enabled: "{{ zookeeper_svc_enabled }}"
    name: zookeeper
    state: "{{ zookeeper_svc_state }}"
  become: true
  tags: [ct-zookeeper]

# --------------------------------
...
